### ISSUE TITLE
Integrate tailwindcss

### ISSUE THREAD

**Issue by josdem** [josdem/sneakers-world-shopping#3]
As a **user**, I want to integrate [tailwindcss](https://tailwindcss.com/) **so that**, I can use style defined by tailwindcss

**Acceptance Criteria**
- I applied style using `tailwindcss` to the home page

**Comment by naijatechgirle** [comment]
Please can I get assigned to this task so I can start working on it?

**Comment by josdem** [comment]
Hi @naijatechgirle  absolutely, your collaboration is appreciated!
