### ISSUE TITLE
Add ESLint validation

### ISSUE THREAD

**Issue by josdem** [josdem/sneakers-world-shopping#8]
As a **user**, I want to add [ESLint](https://eslint.org/) to the project **so that** I can validate format and best practices rules

**Acceptance Criteria**
- I am able to see the ESLint configuration
- I am able to run ESLint validation
- I can see [A11y plugin](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y) integrated

**Comment by VanshVg** [comment]
Hey @josdem I want to work on this issue but I'm just the beginner in Open Source and I'm not much familiar with ESLint either so can you please guide me for this?

**Comment by josdem** [comment]
Hi @VanshVg  [ESLint](https://eslint.org/) is a great way to validate best practices and follow coding standards in Javascript and Typescript. You can start by adding some configuration and running `ESLint` command; please take a look at this repository as a reference. https://github.com/josdem/playwright-applitools I hope this helps.

**Comment by VanshVg** [comment]
Thanx @josdem, I will try to resolve this issue as soon as I can.

**Comment by josdem** [comment]
> Thanx @josdem, I will try to resolve this issue as soon as I can.

Sure, also feel free to let me know if you have any blockers on the road and I can help with those.

**Comment by VanshVg** [comment]
Okay sure.

**Comment by VanshVg** [comment]
I have integrated ESLint into the project and added A11y plugins also.
Here is the .eslintrc.js file
![image](https://github.com/josdem/sneakers-world-shopping/assets/88078960/84c30981-357b-4d37-8433-7f2e63f8b1c0)

But when I'm running npx eslint . command it is showing me some line break error for few files.
![image](https://github.com/josdem/sneakers-world-shopping/assets/88078960/5eba67b4-b29f-422d-9688-3ba3439373cf)

So what should I have to do now?

**Comment by josdem** [comment]
Hi @VanshVg, having so many errors seems like we are not using the correct configuration. Keep in mind these:
- This is a react application
- Language we are using is Javascript
- Since you are learning, try to understand ESLint configuration and options such as `extends` and `rules`.

I suggest this.
Try to add first ESLint with minimum configuration, make it works, then add `a11y` plugin.

**Comment by VanshVg** [comment]
Hey @josdem I tried to solve those errors by making some changes in code(Like spacing, line breaks etc...) according to rules and made some changes in extends and added some rules.

But still getting these two errors.
![image](https://github.com/josdem/sneakers-world-shopping/assets/88078960/5f306bee-c025-4bad-bb2a-d1f0542ac82f)

But I'll have to change variables name so I didn't change it.

**Comment by josdem** [comment]
Hi @VanshVg, It Looks like you made good progress and nailed it down. It is hard for me to suggest without seeing the code. Can you please commit your changes to a branch so I can check out and reproduce the issue?

**Comment by VanshVg** [comment]
Hey @josdem I have committed to feature/7 branch.
You can review the code now.

**Comment by josdem** [comment]
Hi @VanshVg , In the industry, we usually create branches for each feature; therefore I pushed your changes into feature/8 which is the branch for this issue. These are the actions you should do:

- Checkout this branch on your local computer
- Run ESLint command `npx eslint . --ext .js`
- Try to understand the errors and see what is missing in the configuration.

**Comment by VanshVg** [comment]
Hi @josdem I solved all the errors and not getting any errors after running ```npx eslint . --ext .js``` command and also added "jsx-A11Y" plugin in .eslintrc.js and I have committed those changes in feature/8 branch.

**Comment by josdem** [comment]
Thanks @VanshVg; looks good to me, and you did a good job! Feel free to create a PR. Please notice that I added an `npm run lint` command to the `package.json` and information to the `readme` file. In that way, people can execute this validation quickly.

**Comment by VanshVg** [comment]
Hey @josdem I have opened a PR.
Thank You for helping me and guiding me to get into ESLint, Much Appreciated.
